name: Deploying to EC2 AWS

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Mostrar mensaje"
        run: echo "Ejecutando Workflow"
    
      
  
